[tool.poetry]
name = "1337scrapper"
version = "0.1.0"
description = ""
authors = ["Thibaut LANCEMOT <thibaut.lancemot@pm.me>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
